### ISSUE TITLE
Review de um dev da picode

### ISSUE THREAD

**Issue by lucasbaquinoo** [VictorAugDB/desafio_pi-code#1]
Tu é monstrão ein, ta de parabens!!!

![](https://media.giphy.com/media/ekpXiXeyO3nVGFMGTs/giphy.gif)

**Comment by leciric** [comment]
não sei se esse backend é usa as melhores praticas, incremente com esse por favor https://github.com/VictorAugDB/desafio_pi-code/tree/master/backend
